$WALLPAPER = /home/galih/Pictures/Wallpapers/tangerines.jpg

splash = false

wallpaper {
    monitor = eDP-1
    path = $WALLPAPER
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $WALLPAPER
    fit_mode = cover
}
