#!/bin/bash

dunstify -u low -r "696969" "Downloading $QUTE_URL"
yt-dlp -x -f bestaudio -P ~/Music --audio-format mp3 --add-metadata --embed-thumbnail "$QUTE_URL"
dunstify -u low -r "696969" "Finished downloading $QUTE_URL"
